### ISSUE TITLE
Breaks fastboot

### ISSUE THREAD

**Issue by vlascik** [leadiato/ember-theme-changer#1]
This addon breaks fastboot with this error:
```
ReferenceError: document is not defined
    at Class._generateStyleTag (P:\Project\tmp\broccoli_merge_trees-output_path-rLftrlAj.tmp\assets\addon-tree-output\ember-theme-changer\services\theme-changer.js:81:1)
    at Object.initialize (P:\Project\tmp\broccoli_merge_trees-output_path-rLftrlAj.tmp\assets\my-app\instance-initializers\theme-init.js:10:1)
```
Maybe it could use ember-cli-head for the fastboot part instead?

**Comment by leadiato** [comment]
Reading about `ember-cli-head` and it requires to include `{{head-layout}}` in the application template. I'm not sure about adding an extra dependency of this project.
Alternatives?

**Comment by vlascik** [comment]
I'd say this one is pretty standard, used by a lot of addons as well: https://emberobserver.com/code-search?codeQuery=ember-cli-head

**Comment by leadiato** [comment]
Included the use of `ember-cli-head` in the latest release (v0.3.0) and updated the readme with instructions.
Thanks @vlascik for the suggestion!
